language: python
python:
  - "2.7"
  - "pypy"
  - "3.2"
  - "3.3"

env:
  - LIBGIT2=~/libgit2/_install/ LD_LIBRARY_PATH=~/libgit2/_install/lib

before_install:
  - .travis/libgit2.sh

install:
  - pip install --use-mirrors -r requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install --use-mirrors -r requirements2.7-dev.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then pip install --use-mirrors -r requirements2.7-dev.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pip install --use-mirrors -r requirements3-dev.txt; fi

script:
  - nose2
